version: '2.1'
services:
  db:
    image: postgres:10.3-alpine
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_DB=coordinator
    ports:
    - "5432:5432"
    expose:
    - "5432"
    volumes:
    - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
  coordinator:
      image: vastness.io/coordinator:${VERSION}
      depends_on:
        db:
          condition: service_healthy
      ports:
      - "8080:8080"
      expose:
      - "8080"
      volumes:
      - ./db/migration/:/migration
      links:
      - db
      environment:
      - MIGRATION_FILE_LOCATION=/migration
      - COORDINATOR_ADDRESS=0.0.0.0
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgres
volumes:
  postgres-data: {}
