CREATE TABLE PROJECTS (
  ID   SERIAL PRIMARY KEY,
  NAME VARCHAR(256) NOT NULL,
  TYPE VARCHAR(256) NOT NULL,
  UNIQUE (NAME, TYPE)
);

CREATE TABLE REPOSITORIES (
  NAME       VARCHAR(256),
  OWNER      VARCHAR(256),
  TYPE       VARCHAR(256),
  UNIQUE (NAME, OWNER, TYPE),
  PROJECT_ID SERIAL REFERENCES PROJECTS (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BRANCHES (
  META          JSONB,
  ID            SERIAL PRIMARY KEY,
  NAME          VARCHAR(256) NOT NULL,
  REPOSITORY_NAME       VARCHAR(256),
  REPOSITORY_OWNER      VARCHAR(256),
  REPOSITORY_TYPE       VARCHAR(256),
  FOREIGN KEY (REPOSITORY_NAME, REPOSITORY_OWNER, REPOSITORY_TYPE)REFERENCES REPOSITORIES (NAME, OWNER, TYPE) ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE (NAME, REPOSITORY_NAME, REPOSITORY_OWNER, REPOSITORY_TYPE)
);

CREATE TABLE COMMITS (
  META          JSONB,
  SHA          VARCHAR(256) PRIMARY KEY,
  MESSAGE      VARCHAR(256),
  TIMESTAMP    TIMESTAMP NULL,
  AUTHOR_NAME  VARCHAR(256),
  AUTHOR_EMAIL VARCHAR(256),
  ADDED        VARCHAR(256) [],
  MODIFIED     VARCHAR(256) [],
  REMOVED      VARCHAR(256) []
);

CREATE TABLE BRANCH_COMMITS (
  BRANCH_ID  INT REFERENCES BRANCHES (ID),
  COMMIT_SHA VARCHAR(256) REFERENCES COMMITS (SHA),
  UNIQUE (BRANCH_ID, COMMIT_SHA)
);