CREATE TABLE PROJECTS (
  ID   SERIAL PRIMARY KEY,
  NAME VARCHAR(256) NOT NULL UNIQUE,
  TYPE VARCHAR(256) NOT NULL
);

CREATE TABLE REPOSITORIES (
  ID         SERIAL PRIMARY KEY,
  NAME       VARCHAR(256) NOT NULL,
  PROJECT_ID SERIAL REFERENCES PROJECTS (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BRANCHES (
  ID            SERIAL PRIMARY KEY,
  NAME          VARCHAR(256) NOT NULL,
  REPOSITORY_ID SERIAL REFERENCES REPOSITORIES (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE LANGUAGES (
  ID         SERIAL PRIMARY KEY,
  NAME       VARCHAR(256) NOT NULL,
  PERCENTAGE FLOAT,
  BRANCH_ID  SERIAL REFERENCES BRANCHES (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE COMMITS (
  SHA          VARCHAR(256) PRIMARY KEY,
  MESSAGE      VARCHAR(256),
  TIMESTAMP    TIMESTAMP NULL,
  AUTHOR_NAME  VARCHAR(256),
  AUTHOR_EMAIL VARCHAR(256),
  ADDED        VARCHAR(256) [],
  MODIFIED     VARCHAR(256) [],
  REMOVED      VARCHAR(256) [],
  BRANCH_ID    SERIAL REFERENCES BRANCHES (ID) ON DELETE CASCADE ON UPDATE CASCADE
);