CREATE TABLE PROJECTS (
  ID   SERIAL PRIMARY KEY,
  NAME VARCHAR(256) NOT NULL,
  TYPE VARCHAR(256) NOT NULL,
  UNIQUE (NAME, TYPE)
);

CREATE TABLE REPOSITORIES (
  ID         BIGINT PRIMARY KEY,
  NAME       VARCHAR(256) NOT NULL,
  PROJECT_ID SERIAL REFERENCES PROJECTS (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BRANCHES (
  ID            SERIAL PRIMARY KEY,
  NAME          VARCHAR(256) NOT NULL,
  META          JSONB,
  REPOSITORY_ID BIGINT UNIQUE REFERENCES REPOSITORIES (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE (NAME, REPOSITORY_ID)
);

CREATE TABLE COMMITS (
  SHA          VARCHAR(256) PRIMARY KEY,
  MESSAGE      VARCHAR(256),
  TIMESTAMP    TIMESTAMP NULL,
  AUTHOR_NAME  VARCHAR(256),
  AUTHOR_EMAIL VARCHAR(256),
  ADDED        VARCHAR(256) [],
  MODIFIED     VARCHAR(256) [],
  REMOVED      VARCHAR(256) []
);

CREATE TABLE BRANCH_COMMITS (
  BRANCH_ID  INT REFERENCES BRANCHES (ID),
  COMMIT_SHA VARCHAR(256) REFERENCES COMMITS (SHA),
  UNIQUE (BRANCH_ID, COMMIT_SHA)
);