// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vastness-io/coordinator/pkg/repository (interfaces: ProjectRepository)

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/vastness-io/coordinator/pkg/model"
	gormer "github.com/vastness-io/gormer"
	reflect "reflect"
)

// MockProjectRepository is a mock of ProjectRepository interface
type MockProjectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRepositoryMockRecorder
}

// MockProjectRepositoryMockRecorder is the mock recorder for MockProjectRepository
type MockProjectRepositoryMockRecorder struct {
	mock *MockProjectRepository
}

// NewMockProjectRepository creates a new mock instance
func NewMockProjectRepository(ctrl *gomock.Controller) *MockProjectRepository {
	mock := &MockProjectRepository{ctrl: ctrl}
	mock.recorder = &MockProjectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockProjectRepository) EXPECT() *MockProjectRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockProjectRepository) Create(arg0 gormer.DB, arg1 *model.Project) error {
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockProjectRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectRepository)(nil).Create), arg0, arg1)
}

// DB mocks base method
func (m *MockProjectRepository) DB() gormer.DB {
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(gormer.DB)
	return ret0
}

// DB indicates an expected call of DB
func (mr *MockProjectRepositoryMockRecorder) DB() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockProjectRepository)(nil).DB))
}

// Delete mocks base method
func (m *MockProjectRepository) Delete(arg0 gormer.DB, arg1, arg2 string) (bool, error) {
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete
func (mr *MockProjectRepositoryMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectRepository)(nil).Delete), arg0, arg1, arg2)
}

// GetProject mocks base method
func (m *MockProjectRepository) GetProject(arg0 gormer.DB, arg1, arg2 string) (*model.Project, error) {
	ret := m.ctrl.Call(m, "GetProject", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject
func (mr *MockProjectRepositoryMockRecorder) GetProject(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockProjectRepository)(nil).GetProject), arg0, arg1, arg2)
}

// GetProjects mocks base method
func (m *MockProjectRepository) GetProjects(arg0 gormer.DB) ([]*model.Project, error) {
	ret := m.ctrl.Call(m, "GetProjects", arg0)
	ret0, _ := ret[0].([]*model.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjects indicates an expected call of GetProjects
func (mr *MockProjectRepositoryMockRecorder) GetProjects(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjects", reflect.TypeOf((*MockProjectRepository)(nil).GetProjects), arg0)
}

// Update mocks base method
func (m *MockProjectRepository) Update(arg0 gormer.DB, arg1 *model.Project) error {
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockProjectRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProjectRepository)(nil).Update), arg0, arg1)
}
